mysite/blog/urls.py
# Importing necessary modules :
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    # post views here:
    path('', views.post_list, name="post_list"),
    path('<int:id>/', views.post_detail, name="post_detail")

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls',  namespace='blog'))

]

mysite/blog/models.py
from django.db import models
# Importing necessary modules :
from django.utils import timezone
from django.contrib.auth.models import User
# Create your models here.

# Creating Model manager
class PublishManager(models.Manager):
    def get_queryset(self) :
        return super().get_queryset()\
        .filter(status = Post.Status.PUBLISHED)
# Creating Draft manager:
class DraftManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status = Post.Status.DRAFT)
class Post(models.Model):
    # Status subclass:
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB','Published'
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=250)
    body = models.TextField()
    # Many to one relationship
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2, choices=Status.choices, default= Status.DRAFT)
    objects = models.Manager()
    published = PublishManager()
    drafted = DraftManager()
    # Defining a default sort order:
    class Meta:
        # ordering with reverse chonological order by adding -
        ordering = ['-publish']
        # Indexing database
        indexes = [
            models.Index(fields=["-publish"],)
        ]
    def __str__(self) :
        return f"[{self.title}]"

mysite/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from .models import Post
# Create your views here.
def post_list(request):
    posts = Post.published.all()
    return render(request,'blog/post/list.html',{'posts':posts})

def post_detail(request, id):
   try:
      post = Post.published.get(id = id)
   except Post.DoesNotExist:
       raise Http404("Item not found!!")
   return render(request,'blog/post/detail.html',{'post':post})


# def post_detail(request, id):
#     post = get_object_or_404(Post, id=id, status=Post.Status.PUBLISHED)
#     return render(request, 'blog/post/post_detail.html', {'post':post})

mysite/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<title>
        {% block title %}
        {% endblock %}
</title>
<link href="{% static 'css/blog.css'%}" rel="stylesheet">
</head>
<body>
<div id="content">
{% block content %}
{% endblock %}
</div>
<div id="sidebar">
<h2>My blog</h2>
    <p>This is my blog.</p>
</div>
</body>
</html>

mysite/blog/templates/blog/post/detail.html
{% extends "base.html" %} {% block title %}Post Detail page{% endblock %} {%
block content %}
<h1>{{post.title}}</h1>
<p class="date">{{post.publish}}</p>
{{post.body|linebreaks}} {% endblock %}

mysite/blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% block title %} My blogs {% endblock %}
{% block content %}
<h1>My blogs</h1>
{% for post in posts %}
<h2>
    <a href="{% url 'blog:post_detail' post.id %}">
        {{post.title}}
    </a>
</h2>
<p class="date">
    published: {{post.date}} by {{post.author}}
</p>
{{post.body|truncatewords:30|linebreaks}}
{% endfor %}
{% endblock %}